version: "3.7"


services:

  containerManager:
    container_name: spring-container-manager
    image: spring-container-manager
    privileged: true
    build:
      dockerfile: dockerfile
      context: .
    environment:
      NGINX_DOCKER_NAME: nginx-proxy
    volumes:
    - nginx_config:/etc/nginx
    - /var/run/docker.sock:/var/run/docker.sock
    - user_files:/var/theia-users
    command:
      - docker:dind dockerd

volumes:
  nginx_config:
  user_files:
