#Build stage
FROM maven:alpine as build-stage
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src/ /app/src/
RUN mvn package -DskipTests

FROM docker:dind as production-stage
RUN apk add openjdk8-jre
RUN apk --no-cache add curl
COPY --from=build-stage /app/target /app
WORKDIR /app

ENTRYPOINT ["java", "-jar", "./theia-controller-0.0.1-SNAPSHOT.jar"]